build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
formats: all
python:
   install:
   - requirements: doc/sphinx/src/requirements.txt
sphinx:
   configuration: doc/sphinx/conf.py
   fail_on_warning: true
version: 2
