#!/bin/bash

if test `uname -s` = "Darwin"; then
	DIR=$(stat -f %N $0 | xargs dirname)
else
	DIR=$(readlink -f $0 | xargs dirname)
fi

if ! [ -f ${DIR}/cql_config_defines.sh ] || ! [ -x ${DIR}/cql_config_defines.sh ]
then
	echo "missing path configuration file for DataStax Cassandra (cql_config_defines.sh)"
	exit 0
fi
source ${DIR}/cql_config_defines.sh

if [ $# -ne 1 ] && [ $# -ne 2 ]
then
	echo "run: \`$0 --help\` for more help"
	exit 0
fi
if [ $1 == "--help" ]
then
	echo "--help"
	echo "    print this help message"
	echo "--cflags-only-other"
	echo "    get cpp compilation flags"
	echo "--cflags-only-I"
	echo "    get include path"
	echo "--libs"
	echo "    get lib path"
	echo "--modversion"
	echo "    get version"
	exit 0
fi
if [ $1 == "--cflags-only-other" ]
then
	echo "-L${CPP_DRIVER_PATH}/build/"
	exit 0
fi
if [ $1 == "--cflags-only-I" ]
then
	echo "${CPP_DRIVER_PATH}/include/"
	exit 0
fi
if [ $1 == "--libs" ]
then
	echo "-lcassandra_static -luv -lpthread"
	exit 0
fi
if [ $1 == "--modversion" ]
then
	MAJOR=`grep VERSION_MAJOR ${CPP_DRIVER_PATH}/include/cassandra.h | cut -d " " -f 3`
	MINOR=`grep VERSION_MINOR ${CPP_DRIVER_PATH}/include/cassandra.h | cut -d " " -f 3`
	PATCH=`grep VERSION_PATCH ${CPP_DRIVER_PATH}/include/cassandra.h | cut -d " " -f 3`
	echo "${MAJOR}.${MINOR}.${PATCH}"
	exit 0
fi
echo "wrong parameter"
echo "run: \`$0 --help\` for more help"
