#!/bin/bash

sysrepo_lib="libsysrepo"

if [ -z ${YANG_LIBRARY_PATH} ]
then
	YANG_LIBRARY_PATH=/
fi

if test `uname -s` = "Darwin"; then
	DIR=$(stat -f %N $0 | xargs dirname)
else
	DIR=$(readlink -f $0 | xargs dirname)
fi

if ! [ -f ${DIR}/sysrepo_config_defines.sh ] || ! [ -x ${DIR}/sysrepo_config_defines.sh ]
then
	echo "missing path configuration file for Sysrepo (sysrepo_config_defines.sh)"
	exit 0
fi
source ${DIR}/sysrepo_config_defines.sh

if [ $# -ne 1 ] && [ $# -ne 2 ]
then
	echo "run: \`$0 --help\` for more help"
	exit 0
fi
if [ $1 == "--help" ]
then
	echo "sysrepo_config 'option' ['library']"
	echo "options:"
	echo "--help"
	echo "    print this help message"
	echo "--cflags-only-other"
	echo "    get cpp compilation flags"
	echo "--cflags-only-I"
	echo "    get include path"
	echo "--libs"
	echo "    get lib path"
	echo "--modversion"
	echo "    get version"
	echo "--variable=SR_REPOSITORY_LOC"
	echo "    get repo path"
	echo "libraries:"
	echo "    libsysrepo"
	exit 0
else if [ $# -ne 2 ]
	then
		echo "run: \`$0 --help\` for more help"
		exit 0
	else if [ $2 != "libsysrepo" ]
		then
			echo "library $2 not supported"
			echo "run: \`$0 --help\` for more help"
			exit 0
		else
			sysrepo_lib=$2
		fi
	fi
fi
if [ $1 == "--cflags-only-other" ]
then
	exit 0
fi
if [ $1 == "--cflags-only-I" ]
then
	echo "-I${SYSREPO_PATH}/inc/"
	exit 0
fi
if [ $1 == "--libs" ]
then
	echo "-L${SYSREPO_PATH}/build/src -L${SYSREPO_PATH}/build/swig -L$YANG_LIBRARY_PATH -l:${sysrepo_lib}.a -lSysrepo-cpp -lyang -pthread -lpcre -lev -lprotobuf -lavl -lprotobuf-c"
	exit 0
fi
if [ $1 == "--modversion" ]
then
	MAJOR="1"
	MINOR="0"
	PATCH="0"
	echo "${MAJOR}.${MINOR}.${PATCH}"
	exit 0
fi
if [ $1 == "--variable=SR_REPOSITORY_LOC" ]
then
	echo "${SYSREPO_PATH}/build/repository"
fi
echo "wrong parameter"
echo "run: \`$0 --help\` for more help"
